### ISSUE TITLE
React starter pack optimized in cloud9 

### ISSUE THREAD

**Issue by Ruffeng** [codeschool/WatchUsBuild-React#3]
Hi everyone!

I've been checking the videos throug codeschool's website ( that by the way are fantastic), and I'd like to add an improvement. 

I used to work on a cloud IDE called Cloud9, so I wanted to start a new project using your project template that you show on the videos. However, Cloud9 needs a specific configuration for HOST and PORT to work. 

If You're going to `gulpfile.babel.js` and you replace:
`gulp.task('serve', ['transpile'], () => sync.init({ server: 'public' }))`

for: 

```
gulp.task('serve', ['transpile'], () => sync.init({
    server: 'public' ,
    port: process.env.PORT || 8000,
    host: process.env.IP || "localhost"
}))
```

It will work perfect.
I thought it could be interesting to explain here because some people are working with a cloud IDE too and it can save up some time trying to figure out why is not working.

Best!
Rubèn

**Comment by sergiocruz** [comment]
Hi @Ruffeng thanks for the suggestion!

I just pushed a commit that addresses this :)
