### ISSUE TITLE
There's nothing inside src/app.js on start-here branch

### ISSUE THREAD

**Issue by neo** [codeschool/WatchUsBuild-React#4]
According to the video, it should be a file with all codes in it.

**Comment by sergiocruz** [comment]
@neolwc if you look at the 5 minute mark of the video, you'll see that we're using a file called `public/assets/components.js` and we then transfer the contents of that file to `src/app.js`.

Hope this helps!

**Comment by neo** [comment]
Ohh ok, my bad, sorry!
